"""Update id length

Revision ID: 00d6088a0040
Revises: 9c4a502aed37
Create Date: 2026-08-07 09:55:44.870921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00d6088a0040'
down_revision: Union[str, Sequence[str], None] = '9c4a502aed37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'id',
               existing_type=sa.VARCHAR(length=14),
               type_=sqlmodel.sql.sqltypes.AutoString(length=16),
               existing_nullable=False)
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_index(op.f('ix_participant_id'), table_name='participant')
    op.drop_index(op.f('ix_programme_id'), table_name='programme')
    op.drop_index(op.f('ix_rapport_id'), table_name='rapport')
    op.drop_index(op.f('ix_reunion_id'), table_name='reunion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reunion_id'), 'reunion', ['id'], unique=True)
    op.create_index(op.f('ix_rapport_id'), 'rapport', ['id'], unique=True)
    op.create_index(op.f('ix_programme_id'), 'programme', ['id'], unique=True)
    op.create_index(op.f('ix_participant_id'), 'participant', ['id'], unique=True)
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=True)
    op.alter_column('course', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=16),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
