"""Join models

Revision ID: 0cae59c7b96a
Revises: 954dbb59b550
Create Date: 2026-08-18 20:08:38.730929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0cae59c7b96a'
down_revision: Union[str, Sequence[str], None] = '954dbb59b550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combinaison', sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'combinaison', 'course', ['course_id'], ['id'])
    op.add_column('course', sa.Column('reunion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'course', 'reunion', ['reunion_id'], ['id'])
    op.add_column('participant', sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'participant', 'course', ['course_id'], ['id'])
    op.add_column('reunion', sa.Column('programme_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'reunion', 'programme', ['programme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reunion', type_='foreignkey')
    op.drop_column('reunion', 'programme_id')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'course_id')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'reunion_id')
    op.drop_constraint(None, 'combinaison', type_='foreignkey')
    op.drop_column('combinaison', 'course_id')
    # ### end Alembic commands ###
