"""Join Rapport on Course

Revision ID: 320240ae7dbc
Revises: 0cae59c7b96a
Create Date: 2026-08-18 20:28:29.313992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '320240ae7dbc'
down_revision: Union[str, Sequence[str], None] = '0cae59c7b96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rapport', sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'rapport', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rapport', type_='foreignkey')
    op.drop_column('rapport', 'course_id')
    # ### end Alembic commands ###
