"""Add Metrics Table, add updated_at and created_at for all tables.

Revision ID: 386c2b7e5873
Revises: 320240ae7dbc
Create Date: 2026-08-23 17:20:30.241144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '386c2b7e5873'
down_revision: Union[str, Sequence[str], None] = '320240ae7dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('COUNT', 'DURATION', 'PERCENTAGE', name='metrictype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.add_column(
        'combinaison',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.add_column(
        'combinaison',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.execute(
        sa.text(
            "UPDATE combinaison "
            "SET created_at = NOW(), updated_at = NOW() "
            "WHERE created_at IS NULL OR updated_at IS NULL"
        )
    )
    op.alter_column(
        'combinaison',
        'created_at',
        nullable=False,
        server_default=None,
    )
    op.alter_column(
        'combinaison',
        'updated_at',
        nullable=False,
        server_default=None,
    )

    # course
    op.add_column(
        'course',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.add_column(
        'course',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.execute(
        sa.text(
            "UPDATE course "
            "SET created_at = NOW(), updated_at = NOW() "
            "WHERE created_at IS NULL OR updated_at IS NULL"
        )
    )
    op.alter_column(
        'course',
        'created_at',
        nullable=False,
        server_default=None,
    )
    op.alter_column(
        'course',
        'updated_at',
        nullable=False,
        server_default=None,
    )

    # participant
    op.add_column(
        'participant',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.add_column(
        'participant',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.execute(
        sa.text(
            "UPDATE participant "
            "SET created_at = NOW(), updated_at = NOW() "
            "WHERE created_at IS NULL OR updated_at IS NULL"
        )
    )
    op.alter_column(
        'participant',
        'created_at',
        nullable=False,
        server_default=None,
    )
    op.alter_column(
        'participant',
        'updated_at',
        nullable=False,
        server_default=None,
    )

    # programme
    op.add_column(
        'programme',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.add_column(
        'programme',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.execute(
        sa.text(
            "UPDATE programme "
            "SET created_at = NOW(), updated_at = NOW() "
            "WHERE created_at IS NULL OR updated_at IS NULL"
        )
    )
    op.alter_column(
        'programme',
        'created_at',
        nullable=False,
        server_default=None,
    )
    op.alter_column(
        'programme',
        'updated_at',
        nullable=False,
        server_default=None,
    )

    # rapport
    op.add_column(
        'rapport',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.add_column(
        'rapport',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.execute(
        sa.text(
            "UPDATE rapport "
            "SET created_at = NOW(), updated_at = NOW() "
            "WHERE created_at IS NULL OR updated_at IS NULL"
        )
    )
    op.alter_column(
        'rapport',
        'created_at',
        nullable=False,
        server_default=None,
    )
    op.alter_column(
        'rapport',
        'updated_at',
        nullable=False,
        server_default=None,
    )

    # reunion
    op.add_column(
        'reunion',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.add_column(
        'reunion',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True,
            server_default=sa.func.now(),
        )
    )
    op.execute(
        sa.text(
            "UPDATE reunion "
            "SET created_at = NOW(), updated_at = NOW() "
            "WHERE created_at IS NULL OR updated_at IS NULL"
        )
    )
    op.alter_column(
        'reunion',
        'created_at',
        nullable=False,
        server_default=None,
    )
    op.alter_column(
        'reunion',
        'updated_at',
        nullable=False,
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reunion', 'updated_at')
    op.drop_column('reunion', 'created_at')
    op.drop_column('rapport', 'updated_at')
    op.drop_column('rapport', 'created_at')
    op.drop_column('programme', 'updated_at')
    op.drop_column('programme', 'created_at')
    op.drop_column('participant', 'updated_at')
    op.drop_column('participant', 'created_at')
    op.drop_column('course', 'updated_at')
    op.drop_column('course', 'created_at')
    op.drop_column('combinaison', 'updated_at')
    op.drop_column('combinaison', 'created_at')
    op.drop_table('metrics')
    # ### end Alembic commands ###
