"""Add scraper logs

Revision ID: 5abaa67d0446
Revises: 386c2b7e5873
Create Date: 2026-08-24 23:58:34.975634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5abaa67d0446'
down_revision: Union[str, Sequence[str], None] = '386c2b7e5873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='scraperstatus'), nullable=True),
    sa.Column('scraper', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), sa.Computed('EXTRACT(EPOCH FROM (end_time - start_time))', ), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'metrics', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metrics', type_='unique')
    op.drop_table('scraper_logs')
    # ### end Alembic commands ###
