"""Clear data duplicated.

Revision ID: 8ac1704f8809
Revises: 5abaa67d0446
Create Date: 2026-08-28 00:15:04.579243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ac1704f8809'
down_revision: Union[str, Sequence[str], None] = '5abaa67d0446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # programme.raw["programme"]["reunions"]
    op.execute("""
        UPDATE programme
        SET raw = (raw::jsonb #- '{programme,reunions}')::json
        WHERE raw::jsonb #> '{programme,reunions}' IS NOT NULL;
    """)

    # reunion.raw["courses"]
    op.execute("""
        UPDATE reunion
        SET raw = (raw::jsonb - 'courses')::json
        WHERE raw::jsonb ? 'courses';
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
