"""Initial schema

Revision ID: 9c4a502aed37
Revises: 
Create Date: 2026-08-06 23:01:47.395268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c4a502aed37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('is_over', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=True)
    op.create_table('participant',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_id'), 'participant', ['id'], unique=True)
    op.create_table('programme',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('is_scraped', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programme_id'), 'programme', ['id'], unique=True)
    op.create_table('rapport',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rapport_id'), 'rapport', ['id'], unique=True)
    op.create_table('reunion',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reunion_id'), 'reunion', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reunion_id'), table_name='reunion')
    op.drop_table('reunion')
    op.drop_index(op.f('ix_rapport_id'), table_name='rapport')
    op.drop_table('rapport')
    op.drop_index(op.f('ix_programme_id'), table_name='programme')
    op.drop_table('programme')
    op.drop_index(op.f('ix_participant_id'), table_name='participant')
    op.drop_table('participant')
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
