"""Scraper log : Add error fields

Revision ID: f3025f4c7f60
Revises: 8ac1704f8809
Create Date: 2026-09-05 09:54:32.415378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3025f4c7f60'
down_revision: Union[str, Sequence[str], None] = '8ac1704f8809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper_logs', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('scraper_logs', sa.Column('error_traceback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraper_logs', 'error_traceback')
    op.drop_column('scraper_logs', 'error_message')
    # ### end Alembic commands ###
